services:
  - type: web
    name: cloud-todo
    env: node
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cloud-todo-db
          property: connectionString

databases:
  - name: cloud-todo-db
